FROM openjdk:8
MAINTAINER u6k.apps@gmail.com

# Setup Apache Maven
RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean

# Setup work directory
VOLUME /var/my-app
WORKDIR /var/my-app

# Setup docker run setting
EXPOSE 8080

CMD ["mvn", "clean", "package", "site:site"]
